# Generated by Django 5.2.5 on 2025-10-26 20:28

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='service.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='service.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.service'),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='service.service'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'weekday', 'start_time'], name='service_boo_service_1f9fcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("(EXTRACT(EPOCH FROM duration) / 60)::integer %% 30 = 0 AND duration > INTERVAL '0 seconds'", [], output_field=models.BooleanField()), name='duration_multiple_of_30_check'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['service', 'weekday'], name='service_ser_service_03d861_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceschedule',
            constraint=models.UniqueConstraint(fields=('service', 'weekday'), name='unique_service_weekday'),
        ),
    ]
